[package]
name = "scan"
version = "0.1.0"
authors = ["Jonty <jonty.morris@yahoo.co.nz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
